test fail

diff --git a/.github/workflows/test-build-failure.yml b/.github/workflows/test-build-failure.yml
--- a/.github/workflows/test-build-failure.yml
+++ b/.github/workflows/test-build-failure.yml
@@ -21,17 +21,11 @@ jobs:
       - run: |
           ls
           npm run build
-      - name: Display the dir
-        run: echo $PWD
-        shell: bash
       - name: Check Build Status
         run: |
           ls
-          [ ! -d "./_site" ] && echo "Directory /path/to/dir DOES NOT exists." && exit 1
           [ -d "./_site" ] && echo "Directory /path/to/dir exists."
-      - name: Test workflow commands
-        run: |
-          echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
+          [ ! -d "./_site" ] && echo "::error::Documentation Build Error!" && exit 1
       - uses: actions/github-script@v6
         id: check-error
         with:
